In [288]:
import  pandas as pd
import json
from pandas import json_normalize

## Data Understanding

#### Monbien.tn

In [289]:
data = pd.read_json('datasets/monbien_tn/data.json')
df_monbien = json_normalize(data.to_dict('records'))

df_monbien.info()

df_monbien.describe(include='all').T
summary = pd.DataFrame({
    'dtype': df_monbien.dtypes,
    'non_null_count': df_monbien.notnull().sum(),
    'null_count': df_monbien.isnull().sum(),
    'completeness_%': df_monbien.notnull().sum() / len(df_monbien) * 100,
})

duplicates = []
fully_duped_cont = []

for col in df_monbien.columns:
    try:
        # Get the most common value and its frequency
        counts = df_monbien[col].value_counts(dropna=False)
        most_common_freq = counts.iloc[0]
        duplicates.append(most_common_freq / len(df_monbien) * 100)  # % of most common value

        if most_common_freq / len(df_monbien) > 0.99:
            fully_duped_cont.append(counts.index[0])
        else:
            fully_duped_cont.append(None)

    except Exception as e:
        duplicates.append(None)
        fully_duped_cont.append(None)
        print(f"Cannot compute duplicates for column {col}: {e}")

summary['duplicates_in_column'] = duplicates
summary['fully_duplicated_content'] = fully_duped_cont

summary
df_monbien

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6939 entries, 0 to 6938
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   source                6939 non-null   object
 1   url                   6939 non-null   object
 2   annonce_id            6939 non-null   int64
 3   transaction           6939 non-null   object
 4   type_bien             6939 non-null   object
 5   titre                 6939 non-null   object
 6   prix                  6939 non-null   object
 7   surface_m2            6939 non-null   object
 8   pieces                6939 non-null   object
 9   chambres              6939 non-null   object
 10  salles_de_bain        6939 non-null   object
 11  localisation          6939 non-null   object
 12  adresse               6939 non-null   object
 13  description           6939 non-null   object
 14  images_csv            6939 non-null   object
 15  caracteristiques_csv  6939 non-null   object
 16  details_csv           6939 non-null   object
dtypes: int64(1), object(16)
memory usage: 921.7+ KB

,source,url,annonce_id,transaction,type_bien,titre,prix,surface_m2,pieces,chambres,salles_de_bain,localisation,adresse,description,images_csv,caracteristiques_csv,details_csv
0,monbien.tn,https://www.monbien.tn/properties/7599/terrain...,7599,Vente,Terrain,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...,0 DT,4018,,2,,,,Réf: THS063 Nabeul / Hammamet Terrain / à vend...,https://www.monbien.tn/media/cache/resolve/pho...,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...,
1,monbien.tn,https://www.monbien.tn/properties/7592/coquet-...,7592,Vente,Appartement,Coquet studio à vendre à 140 md à hammamet 513...,140 000 DT,,1,2,,,,Réf: AH077 Nabeul / Hammamet Appartement / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Coquet studio à vendre à 140 md à hammamet 513...,
2,monbien.tn,https://www.monbien.tn/properties/7588/villa-t...,7588,Vente,Villa,Villa toute neuve s+3 avec piscine à hammamet ...,650 000 DT,200,3,2,,,,Réf: MHS186 Nabeul / Hammamet Villa / à vendre...,https://www.monbien.tn/media/cache/resolve/pho...,Villa toute neuve s+3 avec piscine à hammamet ...,
3,monbien.tn,https://www.monbien.tn/properties/7596/un-dupl...,7596,Vente,Terrain,Un duplex avec piscine à hammamet nord à vendr...,730 000 DT,220,3,2,,,,Réf: MH112 Nabeul / Hammamet nord Duplex / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Un duplex avec piscine à hammamet nord à vendr...,
4,monbien.tn,https://www.monbien.tn/properties/7594/apparte...,7594,Vente,Appartement,Appartement s+1 avec vue de mer à hammamet à v...,320 000 DT,76,1,2,,,,Réf: AH079 Nabeul / Hammamet centre Appartemen...,https://www.monbien.tn/media/cache/resolve/pho...,Appartement s+1 avec vue de mer à hammamet à v...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6934,monbien.tn,https://www.monbien.tn/properties/7077/bel-app...,7077,Vente,Appartement,Bel appartement s+1 à vendre à afh mrezga 5135...,250 000 DT,90,1,2,,,,Réf: AM091 Nabeul / Mrezga Appartement / à ven...,https://www.monbien.tn/media/cache/resolve/pho...,Bel appartement s+1 à vendre à afh mrezga 5135...,
6935,monbien.tn,https://www.monbien.tn/properties/4831/villa-a...,4831,Location,Villa,"Villa azur à louer à sidi daoud, la marsa",4 200 DT,,,2,,,,Réf: OF91933 Tunis / La marsa Villa / à louer ...,https://www.monbien.tn/media/cache/resolve/pho...,"Villa azur à louer à sidi daoud, la marsa | Vi...",
6936,monbien.tn,https://www.monbien.tn/properties/4840/appart-...,4840,Location,Appartement,Appart s3 rano à louer à cité el ghazela,1 100 DT,,,2,,,,Réf: OF92209 Ariana / Ghazela Appartement / à ...,https://www.monbien.tn/media/cache/resolve/pho...,Appart s3 rano à louer à cité el ghazela | App...,
6937,monbien.tn,https://www.monbien.tn/properties/4848/duplex-...,4848,Location,Duplex,Duplex harmonia à louer à golden tulip,2 900 DT,,,2,,,,Réf: OF92205 Tunis / Gammarth Duplex / à louer...,https://www.monbien.tn/media/cache/resolve/pho...,Duplex harmonia à louer à golden tulip | Duple...,
6938,monbien.tn,https://www.monbien.tn/properties/6434/2-lots-...,6434,Vente,Terrain,2 lots de terrain vue de mer à vendre à jinen ...,0 DT,482,,2,,,,Réf: TBK003 Nabeul / Béni khiar Terrain / à ve...,https://www.monbien.tn/media/cache/resolve/pho...,2 lots de terrain vue de mer à vendre à jinen ...,

#### Tunisie Annonce

In [290]:
data = pd.read_json('datasets/tunisie_annonce/data.json')
df_tunisie_annonces = json_normalize(data.to_dict('records'))
print (df_tunisie_annonces.info())
print (df_tunisie_annonces.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15172 entries, 0 to 15171
Data columns (total 36 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   location             15172 non-null  object
 1   governorate          15172 non-null  object
 2   delegation           15172 non-null  object
 3   locality             15172 non-null  object
 4   property_type        15172 non-null  object
 5   property_subtype     15172 non-null  object
 6   title                15172 non-null  object
 7   description_preview  15156 non-null  object
 8   price_tnd            15124 non-null  float64
 9   price_raw            15172 non-null  object
 10  date_posted          15172 non-null  object
 11  detail_url           15172 non-null  object
 12  listing_page_url     15172 non-null  object
 13  reference_number     15172 non-null  int64
 14  title_full           15172 non-null  object
 15  category_path        15172 non-null  object
 16  category_main        15172 non-null  object
 17  category_type        15172 non-null  object
 18  category_subtype     15172 non-null  object
 19  location_path        15172 non-null  object
 20  country              15172 non-null  object
 21  region               15172 non-null  object
 22  city                 15172 non-null  object
 23  locality_detail      15172 non-null  object
 24  surface_raw          14256 non-null  object
 25  surface_m2           14256 non-null  float64
 26  price_detail         15172 non-null  object
 27  price_eur            15172 non-null  object
 28  price_usd            15172 non-null  object
 29  price_cad            15172 non-null  object
 30  price_dzd            15172 non-null  object
 31  price_mad            15172 non-null  object
 32  description_full     15172 non-null  object
 33  date_inserted        15172 non-null  object
 34  date_modified        15172 non-null  object
 35  address              9443 non-null   object
dtypes: float64(2), int64(1), object(33)
memory usage: 4.2+ MB
None
          price_tnd  reference_number    surface_m2
count  1.512400e+04      1.517200e+04  1.425600e+04
mean   4.113624e+05      3.410153e+06  1.866059e+04
std    1.024580e+06      1.389109e+05  8.637792e+05
min    1.000000e+00      2.358740e+05  1.000000e+00
25%    1.500000e+03      3.426978e+06  9.000000e+01
50%    3.900000e+04      3.436130e+06  1.900000e+02
75%    4.000000e+05      3.444041e+06  5.980000e+02
max    2.600000e+07      3.450755e+06  8.000000e+07

In [291]:
data = pd.read_json('datasets/annonces_immobilieres/data.json')
df_annonces_immobilieres = json_normalize(data.to_dict('records'))
print (df_annonces_immobilieres.head(3))
print (df_annonces_immobilieres.info())
print (df_annonces_immobilieres.describe())

                     source  \
0  annonces-immobilieres.tn
1  annonces-immobilieres.tn
2  annonces-immobilieres.tn

                                                 url  annonce_id transaction  \
0  https://annonces-immobilieres.tn/annonce/detai...         247    location
1  https://annonces-immobilieres.tn/annonce/detai...         248    location
2  https://annonces-immobilieres.tn/annonce/detai...         249    location

   type_bien                                              titre  prix  \
0        NaN  Opportunité Rare Ariana Essoughra. Bâtiment: V...   NaN
1        NaN  Location Annuelle Appartement en Zone Touristi...   NaN
2        NaN  Location Annuelle Villa Neuve à la Zone Touris...   NaN

   surface_m2  pieces  chambres  salles_de_bain                 localisation  \
0         NaN     NaN       NaN             NaN               Ariana, Raoued
1         NaN     NaN       NaN             NaN    Medenine, Djerba - Midoun
2         NaN     NaN       NaN             NaN  Medenine, Djerba-Houmt Souk

   adresse                                        description  \
0      NaN  À vendre : un bâtiment habitation commercial i...
1      NaN  Location annuelle d'un appartement en 1er étag...
2      NaN  Proche de toutes les commodités: Commerces & p...

                                          images_csv  \
0  https://annonces-immobilieres.tn/images/icon/h...
1  https://annonces-immobilieres.tn/images/icon/h...
2  https://annonces-immobilieres.tn/images/icon/h...

                                caracteristiques_csv  \
0  Parking pour:2 voitures,Étages ::5 Appartement...
1  Location annuelle d'un appartement en:1er étag...
2  Elle se compose en RDC d'un espace de vie lumi...

                                         details_csv
0  Jardin,Ascenseur,Cuisine équipée,À vendre : un...
1  Piscine,Cuisine équipée,Chauffage central,Loca...
2  Jardin,Ascenseur,Cuisine équipée,Proche de tou...
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   source                89 non-null     object
 1   url                   89 non-null     object
 2   annonce_id            89 non-null     int64
 3   transaction           89 non-null     object
 4   type_bien             0 non-null      float64
 5   titre                 89 non-null     object
 6   prix                  0 non-null      float64
 7   surface_m2            0 non-null      float64
 8   pieces                0 non-null      float64
 9   chambres              0 non-null      float64
 10  salles_de_bain        0 non-null      float64
 11  localisation          89 non-null     object
 12  adresse               0 non-null      float64
 13  description           89 non-null     object
 14  images_csv            89 non-null     object
 15  caracteristiques_csv  89 non-null     object
 16  details_csv           59 non-null     object
dtypes: float64(7), int64(1), object(9)
memory usage: 11.9+ KB
None
       annonce_id  type_bien  prix  surface_m2  pieces  chambres  \
count   89.000000        0.0   0.0         0.0     0.0       0.0
mean   170.988764        NaN   NaN         NaN     NaN       NaN
std     83.508368        NaN   NaN         NaN     NaN       NaN
min     15.000000        NaN   NaN         NaN     NaN       NaN
25%     76.000000        NaN   NaN         NaN     NaN       NaN
50%    204.000000        NaN   NaN         NaN     NaN       NaN
75%    244.000000        NaN   NaN         NaN     NaN       NaN
max    267.000000        NaN   NaN         NaN     NaN       NaN

       salles_de_bain  adresse
count             0.0      0.0
mean              NaN      NaN
std               NaN      NaN
min               NaN      NaN
25%               NaN      NaN
50%               NaN      NaN
75%               NaN      NaN
max               NaN      NaN

In [292]:
data = pd.read_json('datasets/immobilier_com_tn/data.json')
df_immobilier_com_tn = json_normalize(data.to_dict('records'))
print (df_immobilier_com_tn.head(3))
print (df_immobilier_com_tn.info())
print (df_immobilier_com_tn.describe())

              source                                                url  \
0  immobilier.com.tn  https://www.immobilier.com.tn/annonce/33625/lo...
1  immobilier.com.tn  https://www.immobilier.com.tn/annonce/33645/a-...
2  immobilier.com.tn  https://www.immobilier.com.tn/annonce/33502/al...

   annonce_id transaction    type_bien  \
0       33625    Location       Bureau
1       33645    Location  Appartement
2       33502    Location       Bureau

                                               titre       prix surface_m2  \
0  Location : Local bureautique à louer (Marsa Ma...   2 300 DT        148
1  Location : A louer Etage de villa à Jardin d’E...   1 850 DT        180
2  Location : AL Bureau 346m² au Lac1 - immobilie...  10 700 DT        346

  pieces chambres salles_de_bain  localisation  \
0                                        Tunis
1      3                                Ariana
2                                 Tunis - Lac1

                                             adresse  \
0  rue }; Bureau 148 m² 4 Nous vous proposons à l...
1  rue }; Appartement 180 m² 3 À louer – Étage de...
2  Bloc B, 4ème étage, Immeuble Constance, Rue du...

                                         description images_csv  \
0  Local bureautique à louer (Marsa Mall) Sidi Da...
1  A louer Etage de villa à Jardin d’El menzah 2 ...
2  Bloc B, 4ème étage, Immeuble Constance, Rue du...

                                caracteristiques_csv details_csv
0  Bureau | 148 m² | Étage 1er étage | Climatisat...
1  Appartement | 180 m² | Chauffage Central | Éta...
2                                    Bureau | 346 m²
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   source                896 non-null    object
 1   url                   896 non-null    object
 2   annonce_id            896 non-null    int64
 3   transaction           896 non-null    object
 4   type_bien             896 non-null    object
 5   titre                 896 non-null    object
 6   prix                  896 non-null    object
 7   surface_m2            896 non-null    object
 8   pieces                896 non-null    object
 9   chambres              896 non-null    object
 10  salles_de_bain        896 non-null    object
 11  localisation          896 non-null    object
 12  adresse               896 non-null    object
 13  description           896 non-null    object
 14  images_csv            896 non-null    object
 15  caracteristiques_csv  896 non-null    object
 16  details_csv           896 non-null    object
dtypes: int64(1), object(16)
memory usage: 119.1+ KB
None
         annonce_id
count    896.000000
mean   24829.458705
std     3135.306597
min     1053.000000
25%    23492.500000
50%    24819.500000
75%    26180.000000
max    33663.000000

In [293]:
df_monbien_std = df_monbien.rename(columns={
    "transaction": "contrat",
    "type_bien": "type",
    "surface_m2": "surface",
    "localisation": "ville",
    "caracteristiques_csv": "POI",
    "images_csv": "images"
})

df_monbien_std["pieces"] = df_monbien_std["pieces"].astype(str).str.extract('(\d+)')[0].astype('Int64') +1 
df_monbien_std["prix"] = (
    df_monbien_std["prix"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)  # remove everything except digits
    .astype("Int64")
)
df_monbien_std = df_monbien_std.drop(["chambres", "annonce_id", "source","salles_de_bain","details_csv"], axis=1)
df_monbien_std

,url,contrat,type,titre,prix,surface,pieces,ville,adresse,description,images,POI
0,https://www.monbien.tn/properties/7599/terrain...,Vente,Terrain,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...,0,4018,<NA>,,,Réf: THS063 Nabeul / Hammamet Terrain / à vend...,https://www.monbien.tn/media/cache/resolve/pho...,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...
1,https://www.monbien.tn/properties/7592/coquet-...,Vente,Appartement,Coquet studio à vendre à 140 md à hammamet 513...,140000,,2,,,Réf: AH077 Nabeul / Hammamet Appartement / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Coquet studio à vendre à 140 md à hammamet 513...
2,https://www.monbien.tn/properties/7588/villa-t...,Vente,Villa,Villa toute neuve s+3 avec piscine à hammamet ...,650000,200,4,,,Réf: MHS186 Nabeul / Hammamet Villa / à vendre...,https://www.monbien.tn/media/cache/resolve/pho...,Villa toute neuve s+3 avec piscine à hammamet ...
3,https://www.monbien.tn/properties/7596/un-dupl...,Vente,Terrain,Un duplex avec piscine à hammamet nord à vendr...,730000,220,4,,,Réf: MH112 Nabeul / Hammamet nord Duplex / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Un duplex avec piscine à hammamet nord à vendr...
4,https://www.monbien.tn/properties/7594/apparte...,Vente,Appartement,Appartement s+1 avec vue de mer à hammamet à v...,320000,76,2,,,Réf: AH079 Nabeul / Hammamet centre Appartemen...,https://www.monbien.tn/media/cache/resolve/pho...,Appartement s+1 avec vue de mer à hammamet à v...
...,...,...,...,...,...,...,...,...,...,...,...,...
6934,https://www.monbien.tn/properties/7077/bel-app...,Vente,Appartement,Bel appartement s+1 à vendre à afh mrezga 5135...,250000,90,2,,,Réf: AM091 Nabeul / Mrezga Appartement / à ven...,https://www.monbien.tn/media/cache/resolve/pho...,Bel appartement s+1 à vendre à afh mrezga 5135...
6935,https://www.monbien.tn/properties/4831/villa-a...,Location,Villa,"Villa azur à louer à sidi daoud, la marsa",4200,,<NA>,,,Réf: OF91933 Tunis / La marsa Villa / à louer ...,https://www.monbien.tn/media/cache/resolve/pho...,"Villa azur à louer à sidi daoud, la marsa | Vi..."
6936,https://www.monbien.tn/properties/4840/appart-...,Location,Appartement,Appart s3 rano à louer à cité el ghazela,1100,,<NA>,,,Réf: OF92209 Ariana / Ghazela Appartement / à ...,https://www.monbien.tn/media/cache/resolve/pho...,Appart s3 rano à louer à cité el ghazela | App...
6937,https://www.monbien.tn/properties/4848/duplex-...,Location,Duplex,Duplex harmonia à louer à golden tulip,2900,,<NA>,,,Réf: OF92205 Tunis / Gammarth Duplex / à louer...,https://www.monbien.tn/media/cache/resolve/pho...,Duplex harmonia à louer à golden tulip | Duple...
6938,https://www.monbien.tn/properties/6434/2-lots-...,Vente,Terrain,2 lots de terrain vue de mer à vendre à jinen ...,0,482,<NA>,,,Réf: TBK003 Nabeul / Béni khiar Terrain / à ve...,https://www.monbien.tn/media/cache/resolve/pho...,2 lots de terrain vue de mer à vendre à jinen ...

In [294]:
data = pd.read_json('datasets/tecnocasa/data.json')
df_tecnocasa= json_normalize(data.to_dict('records'))

df_tecnocasa.info()
df_tecnocasa.describe(include='all').T

summary = pd.DataFrame({
    'dtype': df_tecnocasa.dtypes,
    'non_null_count': df_tecnocasa.notnull().sum(),
    'null_count': df_tecnocasa.isnull().sum(),
    'completeness_%': df_tecnocasa.notnull().sum() / len(df_tecnocasa) * 100,
})

duplicates = []
fully_duped_cont = []

for col in df_tecnocasa.columns:
    try:
        # Get the most common value and its frequency
        counts = df_tecnocasa[col].value_counts(dropna=False)
        most_common_freq = counts.iloc[0]
        duplicates.append(most_common_freq / len(df_tecnocasa) * 100)  # % of most common value

        if most_common_freq / len(df_tecnocasa) > 0.99:
            fully_duped_cont.append(counts.index[0])
        else:
            fully_duped_cont.append(None)

    except Exception as e:
        duplicates.append(None)
        fully_duped_cont.append(None)
        print(f"Cannot compute duplicates for column {col}: {e}")

summary['duplicates_in_column %'] = duplicates
summary['fully_duplicated_content'] = fully_duped_cont

summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Columns: 358 entries, ad_type to services.group.9.nome-micro
dtypes: bool(7), datetime64[ns](1), float64(100), int64(26), object(224)
memory usage: 4.8+ MB

,dtype,non_null_count,null_count,completeness_%,duplicates_in_column %,fully_duplicated_content
ad_type,object,1795,0,100.000000,100.000000,estate
id,int64,1795,0,100.000000,0.055710,None
address,object,1795,0,100.000000,1.114206,None
bathrooms,float64,0,1795,0.000000,100.000000,NaN
bedrooms_small,float64,0,1795,0.000000,100.000000,NaN
...,...,...,...,...,...,...
services.group.17.nome-descrizione,object,1,1794,0.055710,99.944290,NaN
services.group.17.option,float64,1,1794,0.055710,99.944290,NaN
services.group.17.surface,float64,0,1795,0.000000,100.000000,NaN
services.group.9.id-micro,object,2,1793,0.111421,99.888579,NaN
services.group.9.nome-micro,object,2,1793,0.111421,99.888579,NaN

In [295]:
for col in df_tecnocasa.columns:
    print(f"{col}")

ad_type
id
address
bathrooms
bedrooms_small
country
data
description
detail_url
detail_url_qr
discount
discount_percentage
estate_other_contract
estate_parent
estates_child
estates_sibling
exclusive
exposure_primary
exposure_secondary
fund_id
height_internal
is_discounted
is_hidden
is_saved
is_tag
last_published_at
latitude
longitude
network
numeric_price
numeric_surface
pdf
publish_map
previous_price
price
price_alternative
private_negotiation
quarter
rooms
services
show_map
status_internal
subtitle
surface
tecnovalore
title
top
data_pdf
agency.aicat
agency.active
agency.address
agency.city.capital
agency.city.id
agency.city.title
agency.city.slug
agency.country
agency.district
agency.district_slug
agency.distance
agency.email
agency.id
agency.images
agency.latitude
agency.longitude
agency.mobile
agency.name
agency.network
agency.opening_hours
agency.phone
agency.phone_proxy
agency.phone_real
agency.province.id
agency.province.title
agency.province.slug
agency.pubbliweb
agency.region.id
agency.region.title
agency.region.slug
agency.sector
agency.status
agency.team
agency.url_agency
agency.url_facebook
agency.url_find
agency.url_image
agency.url_instagram
agency.url_linkedin
agency.url_sell
agency.url_short
agency.url_twitter
agency.vat
agency.whatsapp
agency.zip_code
agency.url_site
city.capital
city.id
city.title
city.slug
contract.id
contract.slug
contract.slug_seohub
contract.slug_estate
contract.title
costs.price
costs.box_price
costs.mortgage_payment
costs.mortgage_payment_value
costs.expenses
dates.build_year
district.id
district.title
district.slug
energy_data.class
energy_data.class_emissions
energy_data.certification_date
energy_data.certification_number
energy_data.certification_type
energy_data.efficiency
energy_data.emissions
energy_data.ep_nren
energy_data.ep_ren
energy_data.icone
energy_data.icone_emissions
energy_data.smile_ce
energy_data.smile_ci
energy_data.building_state
energy_data.heating
energy_data.heating_type
energy_data.heating_power
features.id
features.floor
features.floors
features.box
features.car_places
features.balconies
features.terraces
features.bedrooms
features.furnitured
features.air_conditioning
features.elevator
features.heating
features.garden
features.free
features.category
features.build_year
features.property_type
features.concierge
features.renovation_year
features.inside_renovation_year
media.floor_plans
media.has_realistico
media.has_smartvt360
media.images
media.images_ai
media.map.latitude
media.map.longitude
media.map.exact
media.video
media.virtual_tour
mortgage_data.duration
mortgage_data.external
mortgage_data.fixed_rate
mortgage_data.period
mortgage_data.rate_visible
mortgage_data.user.particulier
mortgage_data.user.professionnel
mortgage_data.user.tre
mortgage_data.payment_type_default
mortgage_data.financial_agency
mortgage_data.financial_agent
mortgage_data.mortgage_duration.0.DURATA_PRO
mortgage_data.mortgage_duration.0.TASSO__FIN
mortgage_data.mortgage_duration.0.CODICE_PRO_FIN
mortgage_data.mortgage_duration.84.DURATA_PRO
mortgage_data.mortgage_duration.84.TASSO__FIN
mortgage_data.mortgage_duration.84.CODICE_PRO_FIN
mortgage_data.mortgage_duration.120.DURATA_PRO
mortgage_data.mortgage_duration.120.TASSO__FIN
mortgage_data.mortgage_duration.120.CODICE_PRO_FIN
mortgage_data.mortgage_duration.180.DURATA_PRO
mortgage_data.mortgage_duration.180.TASSO__FIN
mortgage_data.mortgage_duration.180.CODICE_PRO_FIN
mortgage_data.mortgage_duration.240.DURATA_PRO
mortgage_data.mortgage_duration.240.TASSO__FIN
mortgage_data.mortgage_duration.240.CODICE_PRO_FIN
mortgage_data.mortgage_duration.300.DURATA_PRO
mortgage_data.mortgage_duration.300.TASSO__FIN
mortgage_data.mortgage_duration.300.CODICE_PRO_FIN
mortgage_data.url
points_of_interest.school
points_of_interest.pharmacy
points_of_interest.hospital
points_of_interest.market
points_of_interest.shop
points_of_interest.bar
points_of_interest.restaurant
province.id
province.title
province.slug
region.title
region.slug
sector.id
sector.slug
sector.slug_agency
sector.title
sector.title_plural
type.id
type.title
type.slug
points_of_interest.public_transport
services.rooms
points_of_interest
services.group.0.id-categoria
services.group.0.id-macro
services.group.0.nome-categoria
services.group.0.nome-macro
services.group.0.nome-descrizione
services.group.0.option
services.group.0.surface
services.group.2.id-categoria
services.group.2.id-macro
services.group.2.nome-categoria
services.group.2.nome-macro
services.group.2.nome-descrizione
services.group.2.option
services.group.2.surface
services.group.3.id-categoria
services.group.3.id-macro
services.group.3.nome-categoria
services.group.3.nome-macro
services.group.3.nome-descrizione
services.group.3.option
services.group.3.surface
services.group
services.group.1.id-categoria
services.group.1.id-macro
services.group.1.nome-categoria
services.group.1.nome-macro
services.group.1.nome-descrizione
services.group.1.option
services.group.1.surface
services.group.4.id-categoria
services.group.4.id-macro
services.group.4.nome-categoria
services.group.4.nome-macro
services.group.4.nome-descrizione
services.group.4.option
services.group.4.surface
services.group.5.id-categoria
services.group.5.id-macro
services.group.5.nome-categoria
services.group.5.nome-macro
services.group.5.nome-descrizione
services.group.5.option
services.group.5.surface
services.group.1.id-micro
services.group.1.nome-micro
services.group.2.id-micro
services.group.2.nome-micro
services.group.6.id-categoria
services.group.6.id-macro
services.group.6.nome-categoria
services.group.6.nome-macro
services.group.6.nome-descrizione
services.group.6.option
services.group.6.surface
services.group.7.id-categoria
services.group.7.id-macro
services.group.7.nome-categoria
services.group.7.nome-macro
services.group.7.nome-descrizione
services.group.7.option
services.group.7.surface
services.group.7.id-micro
services.group.7.nome-micro
services.group.4.id-micro
services.group.4.nome-micro
services.group.5.id-micro
services.group.5.nome-micro
services.group.0.id-micro
services.group.0.nome-micro
services.group.3.id-micro
services.group.3.nome-micro
services.group.6.id-micro
services.group.6.nome-micro
services.group.8.id-categoria
services.group.8.id-macro
services.group.8.nome-categoria
services.group.8.nome-macro
services.group.8.nome-descrizione
services.group.8.option
services.group.8.surface
services.group.9.id-categoria
services.group.9.id-macro
services.group.9.nome-categoria
services.group.9.nome-macro
services.group.9.nome-descrizione
services.group.9.option
services.group.9.surface
services.group.8.id-micro
services.group.8.nome-micro
services.group.10.id-categoria
services.group.10.id-macro
services.group.10.nome-categoria
services.group.10.nome-macro
services.group.10.nome-descrizione
services.group.10.option
services.group.10.surface
services.group.10.id-micro
services.group.10.nome-micro
services.group.11.id-categoria
services.group.11.id-macro
services.group.11.nome-categoria
services.group.11.nome-macro
services.group.11.nome-descrizione
services.group.11.option
services.group.11.surface
services.group.11.id-micro
services.group.11.nome-micro
services.group.12.id-categoria
services.group.12.id-macro
services.group.12.nome-categoria
services.group.12.nome-macro
services.group.12.nome-descrizione
services.group.12.option
services.group.12.surface
services.group.13.id-categoria
services.group.13.id-macro
services.group.13.nome-categoria
services.group.13.nome-macro
services.group.13.nome-descrizione
services.group.13.option
services.group.13.surface
services.group.14.id-categoria
services.group.14.id-macro
services.group.14.nome-categoria
services.group.14.nome-macro
services.group.14.nome-descrizione
services.group.14.option
services.group.14.surface
services.group.15.id-categoria
services.group.15.id-macro
services.group.15.nome-categoria
services.group.15.nome-macro
services.group.15.nome-descrizione
services.group.15.option
services.group.15.surface
services.group.14.id-micro
services.group.14.nome-micro
services.group.17.id-categoria
services.group.17.id-macro
services.group.17.nome-categoria
services.group.17.nome-macro
services.group.17.nome-descrizione
services.group.17.option
services.group.17.surface
services.group.9.id-micro
services.group.9.nome-micro

In [296]:
data = pd.read_json('datasets/Bigdatis/data1.json')  # single object
df_bigdatis = json_normalize(data.to_dict('records'))  # wrap in a list

print (df_bigdatis.info())
print (df_bigdatis  .describe())

df_bigdatis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27048 entries, 0 to 27047
Data columns (total 31 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          27048 non-null  int64
 1   idsAlt                      27048 non-null  object
 2   sources                     27048 non-null  object
 3   title                       27048 non-null  object
 4   description                 27048 non-null  object
 5   price                       22286 non-null  float64
 6   area                        16097 non-null  float64
 7   flags                       27048 non-null  object
 8   thumbnailUrl                27048 non-null  object
 9   images                      27048 non-null  object
 10  imageUrls                   27048 non-null  object
 11  locationId                  27048 non-null  int64
 12  sellerTypes                 27048 non-null  object
 13  contacts                    27048 non-null  object
 14  activeContactsCount         27048 non-null  int64
 15  adsCount                    27048 non-null  int64
 16  activeAdsCount              27048 non-null  int64
 17  sourcesCount                27048 non-null  int64
 18  activeSourcesCount          27048 non-null  int64
 19  firstSeenAt                 27048 non-null  object
 20  createdAt                   23043 non-null  object
 21  modifiedAt                  23043 non-null  object
 22  priceDroppedAt              23043 non-null  object
 23  timestamp                   23043 non-null  datetime64[ns]
 24  priceTimestamp              23043 non-null  object
 25  comments                    27048 non-null  object
 26  commentsCount               27048 non-null  int64
 27  properties.transactionType  27048 non-null  object
 28  properties.sellerType       27048 non-null  object
 29  properties.propertyType     27048 non-null  object
 30  properties.typology         18518 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(8), object(20)
memory usage: 6.4+ MB
None
                 id         price          area    locationId  \
count  2.704800e+04  22286.000000  16097.000000  27048.000000
mean   1.237042e+06   2202.992910    191.046655   2125.953823
min    1.109660e+06    350.000000     15.000000      1.000000
25%    1.245300e+06   1150.000000     65.000000    300.000000
50%    1.249255e+06   1600.000000     75.000000    311.000000
75%    1.254077e+06   3800.000000    190.000000   3961.000000
max    1.254098e+06   7000.000000    600.000000   5321.000000
std    3.562884e+04   1797.202977    207.983326   1958.917074

       activeContactsCount      adsCount  activeAdsCount  sourcesCount  \
count         27048.000000  27048.000000    27048.000000  27048.000000
mean              1.379917     18.648033        3.648144      2.360064
min               0.000000      1.000000        1.000000      1.000000
25%               1.000000      1.000000        1.000000      1.000000
50%               1.000000      9.000000        1.000000      1.000000
75%               1.000000     20.000000        4.000000      3.000000
max               6.000000    118.000000       21.000000      9.000000
std               1.257682     29.019392        4.834910      2.033806

       activeSourcesCount                      timestamp  commentsCount
count        27048.000000                          23043        27048.0
mean             2.265084  2026-02-21 19:21:27.318317824            0.0
min              1.000000            2026-02-21 18:50:28            0.0
25%              1.000000            2026-02-21 18:55:43            0.0
50%              1.000000            2026-02-21 18:57:15            0.0
75%              3.000000            2026-02-21 19:24:58            0.0
max              8.000000            2026-02-21 21:46:30            0.0
std              1.825121                            NaN            0.0

,id,idsAlt,sources,title,description,price,area,flags,thumbnailUrl,images,...,modifiedAt,priceDroppedAt,timestamp,priceTimestamp,comments,commentsCount,properties.transactionType,properties.sellerType,properties.propertyType,properties.typology
0,1254077,[],"[{'sourceId': 2, 'lastModified': 1771701898, '...",محل تجاري للكراء,📢 محل تجاري للكراء – خزامة الغربية (سوسة)\n\nم...,500.0,NaN,[],56215/28107556_f4b0b0f8b8b87cfe.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 19:24:58,2026-02-21 19:24:56,2026-02-21 19:24:58,2026-02-21 19:24:56,[],0,rental,private,commercialPremise,NaN
1,1254079,[],"[{'sourceId': 2, 'lastModified': 1771703278, '...",a louer s+1 haut standing,🏡 À louer – 3 Appartements de type S+1 neufs ....,800.0,55.0,[new],56215/28107562_80b8393191904056.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 19:47:58,2026-02-21 19:47:56,2026-02-21 19:47:58,2026-02-21 19:47:56,[],0,rental,agency,flat,s+1
2,1254083,[],"[{'sourceId': 12, 'lastModified': None, 'price...",دار للكراء للطالبات,حي لحبيب شارع سيدي عبيد نهج مقابل توابل ملاك ...,NaN,NaN,[],56215/28107578_eade3c3e3d387ccb.jpg,[{'url': 'https://b3g4.fra01.idrivee2-68.com/i...,...,None,None,NaT,None,[],0,rental,private,house,NaN
3,1254081,[],"[{'sourceId': 2, 'lastModified': 1771707510, '...",Local commercial 15 m²,"à louer local commercial,\nemplacement :\nsitu...",1400.0,15.0,[],56215/28107603_33d4b2fefa7e7d3f.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 20:58:30,2026-02-20 23:00:00,2026-02-21 20:58:30,2026-02-20 23:00:00,[],0,rental,private,commercialPremise,NaN
4,1183174,[],"[{'sourceId': 14, 'lastModified': 1771707661, ...",S+1 en location,"Cet appartement, jamais habité, est situé au p...",350.0,70.0,[new],56215/28107604_f7b4b3b0b4bc34c4.jpg,[{'url': 'https://cdn-media.medialabtc.it/tn/a...,...,2026-02-21 21:01:01,2025-11-01 09:21:13,2026-02-21 21:01:01,2025-11-01 09:21:13,[],0,rental,agency,flat,s+1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27043,1251466,[1251839],"[{'sourceId': 2, 'lastModified': 1771700104, '...",MENZAH 9 B : APPARTEMENT S+2 À LOUER,📍MENZAH 9 B : APPARTEMENT S+2 À LOUER \n\nL’a...,1650.0,120.0,"[elevator, parking]",56215/28107535_114006460323f3c0.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:04,2026-02-15 23:00:00,2026-02-21 18:55:04,2026-02-15 23:00:00,[],0,rental,agency,flat,s+2
27044,1252481,[],"[{'sourceId': 2, 'lastModified': 1771700121, '...",📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,1450.0,NaN,[],56215/28107536_f8fcf8f8f9fcfef8.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:21,2026-02-11 23:00:00,2026-02-21 18:55:21,2026-02-11 23:00:00,[],0,rental,agency,villaFloor,s+2
27045,1251569,[],"[{'sourceId': 2, 'lastModified': 1771700143, '...",📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,4200.0,600.0,[],56215/28107537_11031921ab6b00ca.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:43,2026-02-16 15:03:14,2026-02-21 18:55:43,2026-02-16 15:03:14,[],0,rental,agency,house,s+7
27046,1210068,[1210134],"[{'sourceId': 2, 'lastModified': 1771700169, '...",📍 CITE ENNOZHA - ARIANA : DES BUREAUX H+2 À LOUER,L’agence #MON_RÉSEAU met à la location des bur...,1150.0,NaN,[],56215/28107538_e1e1f1715bdbfaf2.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:56:09,2025-12-14 20:04:36,2026-02-21 18:56:09,2025-12-14 20:04:36,[],0,rental,agency,office,a+2
27047,1109660,[1110068],"[{'sourceId': 2, 'lastModified': 1771700214, '...",ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A ...,📍ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A...,1200.0,70.0,"[furnished, elevator, parking, balcony, heatin...",56215/28107539_3ab131686868c8cc.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:56:54,2025-08-04 12:27:06,2026-02-21 18:56:54,2025-08-04 12:27:06,[],0,rental,agency,flat,s+1

## Dataset Standarisation

### Master Raw Column Mapping for Real Estate Datasets

|| <span style="color:#1f77b4;">description</span>|| <span style="color:#1f77b4;">titre</span>|| <span style="color:#1f77b4;">adresse</span> || <span style="color:#ff7f0e;">url</span> || <span style="color:#2ca02c;">latitude</span> | <span style="color:#2ca02c;">longitude</span> || <span style="color:#d62728;">prix</span> || <span style="color:#9467bd;">surface</span> || <span style="color:#8c564b;">pieces</span> || <span style="color:#1f77b4;">ville</span> || <span style="color:#ff7f0e;">contrat</span> || <span style="color:#2ca02c;">etage</span> || <span style="color:#2ca02c;">clim</span> || <span style="color:#2ca02c;">ascenseur</span> || <span style="color:#2ca02c;">chauffage</span> || <span style="color:#2ca02c;">jardin</span> || <span style="color:#1f77b4;">standing</span> || <span style="color:#9467bd;">annee_constr</span> || <span style="color:#17becf;">ecole</span> || <span style="color:#17becf;">pharmacie</span> || <span style="color:#17becf;">hopital</span> || <span style="color:#17becf;">marche</span> || <span style="color:#17becf;">magasin</span> || <span style="color:#17becf;">bar</span> || <span style="color:#17becf;">restaurant</span> || <span style="color:#1f77b4;">region</span> || <span style="color:#1f77b4;">type</span> || <span style="color:#17becf;">transport</span> || <span style="color:#2ca02c;">aire_jeux</span> || <span style="color:#2ca02c;">alarme</span> || <span style="color:#2ca02c;">balcon</span> || <span style="color:#8c564b;">brique</span> || <span style="color:#ff7f0e;">cafeteria</span> || <span style="color:#2ca02c;">divise</span> || <span style="color:#2ca02c;">doublure</span> || <span style="color:#2ca02c;">enduction</span> || <span style="color:#2ca02c;">entree_indep</span> || <span style="color:#2ca02c;">escalier_ext</span> || <span style="color:#ff7f0e;">four</span> || <span style="color:#2ca02c;">garage</span> || <span style="color:#2ca02c;">gardien</span> || <span style="color:#2ca02c;">interphone</span> || <span style="color:#2ca02c;">jardin_ext</span> || <span style="color:#2ca02c;">parking_pub</span> || <span style="color:#2ca02c;">pergola_abris</span> || <span style="color:#2ca02c;">place_parking</span> || <span style="color:#2ca02c;">plafond</span> || <span style="color:#8c564b;">potager</span> || <span style="color:#9467bd;">poutres</span> || <span style="color:#9467bd;">recouvrement</span> || <span style="color:#9467bd;">rustique</span> || <span style="color:#ff7f0e;">reception</span> || <span style="color:#d62728;">anti_incendie</span> || <span style="color:#2ca02c;">terrasse</span> || <span style="color:#2ca02c;">videophone</span> || <span style="color:#2ca02c;">cour_interieure</span> || <span style="color:#1f77b4;">code_postal</span> || <span style="color:#1f77b4;">date_publication</span> || <span style="color:#1f77b4;">date_scrapping</span>

### Tecnocasa

In [297]:
# Load your datasets
# df_monbien 
# df_tunisie_annonces
# df_annonces_immobilieres
# df_immobilier_com_tn
# df_tecnocasa
# df_Bigdatis

# List of columns to extract
columns_to_extract = [
    "title",
    "address",
    "description",
    "detail_url", 
    "latitude",
    "longitude",
    "numeric_price",
    "numeric_surface",
    "rooms",
    "city.slug",
    "contract.title",
    "features.floor",
    "features.air_conditioning",
    "features.elevator",
    "features.heating",
    "features.garden",
    "features.category",
    "features.build_year",
    "points_of_interest.school",
    "points_of_interest.pharmacy",
    "points_of_interest.hospital",
    "points_of_interest.market",
    "points_of_interest.shop",
    "points_of_interest.bar",
    "points_of_interest.restaurant",
    "region.slug",
    "type.slug",
    "points_of_interest.public_transport",
    "services.group.2.nome-macro",
    "services.group.0.nome-macro",
    "services.group.6.nome-macro",
    "last_published_at"
]

# Keep only columns that actually exist in the dataframe (avoid KeyError)
existing_columns = [col for col in columns_to_extract if col in df_tecnocasa.columns]

# Create the new dataset
df_tecnocasa_std = df_tecnocasa[existing_columns].copy()

# Check result
print(df_tecnocasa_std.head())
print(df_tecnocasa_std.info())

                    title      address  \
0  Villa jumelée en vente    Rue Bhira
1            S+2 en vente  Rue soltana
2        Triplex en vente   Borj taleb
3            S+2 en vente   Beb mateur
4            S+2 en vente   Rue Rawebi

                                         description  \
0  <p>Villa à deux étages offrant de beaux volume...
1  <p> Cet appartement <strong data-start="125" d...
2  <p data-start="0" data-end="709" data-is-last-...
3  <p>Cet appartemen Situé au <strong>deuxième ét...
4  <p> cet appartement <strong data-start="82" da...

                                          detail_url   latitude  longitude  \
0  https://www.tecnocasa.tn/vendre/villa/bizerte/...  37.293402   9.854981
1  https://www.tecnocasa.tn/vendre/appartement/bi...  37.289502   9.848741
2  https://www.tecnocasa.tn/vendre/appartement/bi...  37.279702   9.843971
3  https://www.tecnocasa.tn/vendre/appartement/bi...  37.267202   9.868231
4  https://www.tecnocasa.tn/vendre/appartement/bi...  37.284502   9.870201

   numeric_price  numeric_surface     rooms city.slug  ...  \
0         550000              196      None   bizerte  ...
1         330000              130  3 pièces   bizerte  ...
2         200000              205      None   bizerte  ...
3         150000               51  3 pièces   bizerte  ...
4         330000              100  3 pièces   bizerte  ...

                             points_of_interest.shop  \
0  [{'name': 'Proxi', 'class': 'shop', 'subclass'...
1  [{'name': 'Frip', 'class': 'shop', 'subclass':...
2  [{'name': 'Frip', 'class': 'shop', 'subclass':...
3  [{'name': 'Proxi', 'class': 'shop', 'subclass'...
4  [{'name': 'Proxi', 'class': 'shop', 'subclass'...

                              points_of_interest.bar  \
0  [{'name': 'The Palm Garden Bar', 'class': 'bar...
1                                                NaN
2                                                NaN
3  [{'name': 'The Palm Garden Bar', 'class': 'bar...
4  [{'name': 'The Palm Garden Bar', 'class': 'bar...

                       points_of_interest.restaurant  region.slug  \
0  [{'name': 'Bake & Bake', 'class': 'restaurant'...  nord-est-ne
1  [{'name': 'Bake & Bake', 'class': 'restaurant'...  nord-est-ne
2  [{'name': 'The Garage', 'class': 'restaurant',...  nord-est-ne
3  [{'name': 'Restaurants', 'class': 'restaurant'...  nord-est-ne
4  [{'name': 'Bake & Bake', 'class': 'restaurant'...  nord-est-ne

     type.slug                points_of_interest.public_transport  \
0        villa                                                NaN
1  appartement  [{'name': 'Bizerte', 'class': 'bus', 'subclass...
2  appartement  [{'name': 'Bizerte', 'class': 'railway', 'subc...
3  appartement  [{'name': 'Bizerte', 'class': 'railway', 'subc...
4  appartement  [{'name': 'Bizerte', 'class': 'railway', 'subc...

  services.group.2.nome-macro  services.group.0.nome-macro  \
0                         NaN                          NaN
1                         NaN                          NaN
2                         NaN                          NaN
3                         NaN                          NaN
4                         NaN                          NaN

  services.group.6.nome-macro   last_published_at
0                         NaN 2026-01-21 12:40:58
1                         NaN 2026-01-13 15:09:03
2                         NaN 2025-12-15 18:06:31
3                         NaN 2025-09-03 11:57:17
4                         NaN 2025-12-04 18:17:08

[5 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 32 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   title                                1795 non-null   object
 1   address                              1795 non-null   object
 2   description                          1795 non-null   object
 3   detail_url                           1795 non-null   object
 4   latitude                             1795 non-null   float64
 5   longitude                            1795 non-null   float64
 6   numeric_price                        1795 non-null   int64
 7   numeric_surface                      1795 non-null   int64
 8   rooms                                1079 non-null   object
 9   city.slug                            1795 non-null   object
 10  contract.title                       1795 non-null   object
 11  features.floor                       1795 non-null   object
 12  features.air_conditioning            388 non-null    object
 13  features.elevator                    1795 non-null   object
 14  features.heating                     473 non-null    object
 15  features.garden                      1795 non-null   object
 16  features.category                    1786 non-null   object
 17  features.build_year                  1705 non-null   float64
 18  points_of_interest.school            1663 non-null   object
 19  points_of_interest.pharmacy          1591 non-null   object
 20  points_of_interest.hospital          1362 non-null   object
 21  points_of_interest.market            1573 non-null   object
 22  points_of_interest.shop              1559 non-null   object
 23  points_of_interest.bar               1112 non-null   object
 24  points_of_interest.restaurant        1645 non-null   object
 25  region.slug                          1795 non-null   object
 26  type.slug                            1795 non-null   object
 27  points_of_interest.public_transport  1531 non-null   object
 28  services.group.2.nome-macro          195 non-null    object
 29  services.group.0.nome-macro          55 non-null     object
 30  services.group.6.nome-macro          48 non-null     object
 31  last_published_at                    1795 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(2), object(26)
memory usage: 448.9+ KB
None

In [298]:
columns = [
    "services.group.2.nome-macro",
    "services.group.0.nome-macro",
    "services.group.6.nome-macro"
]

all_values = set()

for col in columns:
    if col in df_tecnocasa.columns:
        values = df_tecnocasa[col].dropna().unique()
        all_values.update(values)

# Sort final combined list
combined_unique = sorted(all_values)

print("===== Combined Unique values =====")
for val in combined_unique:
    print(val)

print("\nTotal unique values:", len(combined_unique))

===== Combined Unique values =====
Aire de jeux
Alarme
Ascenseur
Balcon
Brique
Cafétéria
Divisé
Enduction, Recouvrement, Doublure ...
Entrée indépendante
Escalier extérieure
Four
Garage
Gardien
Interphone
Jardin
Parking public
Pergola/Abris
Place de parking
Plafond
Potager/Jardin Potager
Poutres Apparentes
Rustique
Réception
Système anti-incendie
Terrasse
Vidéophone
cour intérieure

Total unique values: 27

In [299]:
from sklearn.preprocessing import MultiLabelBinarizer

columns = [
    "services.group.2.nome-macro",
    "services.group.0.nome-macro",
    "services.group.6.nome-macro"
]

# Combine all 3 columns into one list per row
def combine_services(row):
    values = []
    for col in columns:
        if col in df_tecnocasa_std.columns and pd.notna(row[col]):
            values.extend(str(row[col]).split(","))
    return [v.strip() for v in values if v.strip() != ""]

df_tecnocasa_std["caracteristiques"] = df_tecnocasa_std.apply(combine_services, axis=1)
df_tecnocasa_std["caracteristiques"].value_counts()

caracteristiques
[]                                                 1543
[Balcon]                                             61
[Terrasse]                                           42
[Ascenseur]                                          20
[Place de parking]                                   19
[Jardin]                                             12
[Interphone]                                          9
[Potager/Jardin Potager]                              8
[Garage]                                              6
[Entrée indépendante]                                 5
[cour intérieure]                                     4
[Vidéophone]                                          3
[Gardien]                                             3
[Place de parking, Balcon]                            3
[Terrasse, Garage]                                    3
[Ascenseur, Place de parking]                         3
[Plafond]                                             2
[Escalier extérieure]                                 2
[Four]                                                2
[Balcon, Place de parking]                            2
[Place de parking, Ascenseur]                         2
[Parking public, Balcon]                              2
[Balcon, Parking public]                              2
[Réception]                                           2
[Pergola/Abris]                                       2
[Terrasse, Jardin]                                    2
[Parking public]                                      2
[Alarme]                                              2
[Brique, Balcon]                                      1
[Terrasse, Entrée indépendante]                       1
[Balcon, Poutres Apparentes]                          1
[Interphone, Balcon]                                  1
[Place de parking, Balcon, Cafétéria]                 1
[Enduction, Recouvrement, Doublure ..., Balcon]       1
[Terrasse, Plafond]                                   1
[Place de parking, Terrasse]                          1
[Ascenseur, Balcon]                                   1
[Pergola/Abris, Balcon, Place de parking]             1
[Jardin, Terrasse]                                    1
[Jardin, Place de parking, Balcon]                    1
[Four, Jardin]                                        1
[cour intérieure, Terrasse]                           1
[Aire de jeux]                                        1
[Balcon, Rustique]                                    1
[Balcon, Système anti-incendie]                       1
[Divisé]                                              1
[Escalier extérieure, Balcon, Alarme]                 1
[Balcon, Entrée indépendante]                         1
[Place de parking, Jardin]                            1
[Réception, Place de parking]                         1
[Brique]                                              1
[Enduction, Recouvrement, Doublure ...]               1
[Potager/Jardin Potager, Terrasse]                    1
[Terrasse, Ascenseur]                                 1
[Ascenseur, Alarme]                                   1
Name: count, dtype: int64

In [300]:
#mlb = MultiLabelBinarizer()
#
#encoded = mlb.fit_transform(df_tecnocasa_std["combined_services"])
#
#services_encoded = pd.DataFrame(
#    encoded,
#    columns=mlb.classes_,
#    index=df_tecnocasa_std.index
#)

In [301]:
#df_tecnocasa_std = pd.concat(
#    [df_tecnocasa_std.drop(columns=columns + ["combined_services"]), services_encoded],
#    axis=1
#)

In [302]:
df_tecnocasa_std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 33 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   title                                1795 non-null   object
 1   address                              1795 non-null   object
 2   description                          1795 non-null   object
 3   detail_url                           1795 non-null   object
 4   latitude                             1795 non-null   float64
 5   longitude                            1795 non-null   float64
 6   numeric_price                        1795 non-null   int64
 7   numeric_surface                      1795 non-null   int64
 8   rooms                                1079 non-null   object
 9   city.slug                            1795 non-null   object
 10  contract.title                       1795 non-null   object
 11  features.floor                       1795 non-null   object
 12  features.air_conditioning            388 non-null    object
 13  features.elevator                    1795 non-null   object
 14  features.heating                     473 non-null    object
 15  features.garden                      1795 non-null   object
 16  features.category                    1786 non-null   object
 17  features.build_year                  1705 non-null   float64
 18  points_of_interest.school            1663 non-null   object
 19  points_of_interest.pharmacy          1591 non-null   object
 20  points_of_interest.hospital          1362 non-null   object
 21  points_of_interest.market            1573 non-null   object
 22  points_of_interest.shop              1559 non-null   object
 23  points_of_interest.bar               1112 non-null   object
 24  points_of_interest.restaurant        1645 non-null   object
 25  region.slug                          1795 non-null   object
 26  type.slug                            1795 non-null   object
 27  points_of_interest.public_transport  1531 non-null   object
 28  services.group.2.nome-macro          195 non-null    object
 29  services.group.0.nome-macro          55 non-null     object
 30  services.group.6.nome-macro          48 non-null     object
 31  last_published_at                    1795 non-null   datetime64[ns]
 32  caracteristiques                     1795 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(27)
memory usage: 462.9+ KB

In [303]:
# Création d'un dictionnaire de renommage
rename_dict = {
    "title": "titre",
    "description": "description",
    "address": "adresse",
    "detail_url": "url",
    "latitude": "latitude",
    "longitude": "longitude",
    "numeric_price": "prix",
    "numeric_surface": "surface",
    "rooms": "pieces",
    "city.slug": "ville",
    "contract.title": "contrat",
    "features.floor": "etage",
    "features.air_conditioning": "clim",
    "features.elevator": "ascenseur",
    "features.heating": "chauffage",
    "features.garden": "jardin",
    "features.category": "standing",
    "features.build_year": "annee_constr",
    "points_of_interest.school": "ecole",
    "points_of_interest.pharmacy": "pharmacie",
    "points_of_interest.hospital": "hopital",
    "points_of_interest.market": "marche",
    "points_of_interest.shop": "magasin",
    "points_of_interest.bar": "bar",
    "points_of_interest.restaurant": "restaurant",
    "region.slug": "region",
    "type.slug": "type",
    "points_of_interest.public_transport": "transport",
    #"Aire de jeux": "aire_jeux",
    #"Alarme": "alarme",
    #"Ascenseur": "ascenseur_bat",
    #"Balcon": "balcon",
    #"Brique": "brique",
    #"Cafétéria": "cafeteria",
    #"Divisé": "divise",
    #"Doublure ...": "doublure",
    #"Enduction": "enduction",
    #"Entrée indépendante": "entree_indep",
    #"Escalier extérieure": "escalier_ext",
    #"Four": "four",
    #"Garage": "garage",
    #"Gardien": "gardien",
    #"Interphone": "interphone",
    #"Jardin": "jardin_ext",
    #"Parking public": "parking_pub",
    #"Pergola/Abris": "pergola_abris",
    #"Place de parking": "place_parking",
    #"Plafond": "plafond",
    #"Potager/Jardin Potager": "potager",
    #"Poutres Apparentes": "poutres",
    #"Recouvrement": "recouvrement",
    #"Rustique": "rustique",
    #"Réception": "reception",
    #"Système anti-incendie": "anti_incendie",
    #"Terrasse": "terrasse",
    #"Vidéophone": "videophone",
    #"cour intérieure": "cour_interieure"
}

# Appliquer le renommage
df_tecnocasa_std = df_tecnocasa_std.rename(columns=rename_dict)

# Vérification
print(df_tecnocasa_std.columns)

Index(['titre', 'adresse', 'description', 'url', 'latitude', 'longitude',
       'prix', 'surface', 'pieces', 'ville', 'contrat', 'etage', 'clim',
       'ascenseur', 'chauffage', 'jardin', 'standing', 'annee_constr', 'ecole',
       'pharmacie', 'hopital', 'marche', 'magasin', 'bar', 'restaurant',
       'region', 'type', 'transport', 'services.group.2.nome-macro',
       'services.group.0.nome-macro', 'services.group.6.nome-macro',
       'last_published_at', 'caracteristiques'],
      dtype='object')

In [304]:
df_tecnocasa_std.info()
df_tecnocasa_std.describe(include='all').T
df_tecnocasa_std

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   titre                        1795 non-null   object
 1   adresse                      1795 non-null   object
 2   description                  1795 non-null   object
 3   url                          1795 non-null   object
 4   latitude                     1795 non-null   float64
 5   longitude                    1795 non-null   float64
 6   prix                         1795 non-null   int64
 7   surface                      1795 non-null   int64
 8   pieces                       1079 non-null   object
 9   ville                        1795 non-null   object
 10  contrat                      1795 non-null   object
 11  etage                        1795 non-null   object
 12  clim                         388 non-null    object
 13  ascenseur                    1795 non-null   object
 14  chauffage                    473 non-null    object
 15  jardin                       1795 non-null   object
 16  standing                     1786 non-null   object
 17  annee_constr                 1705 non-null   float64
 18  ecole                        1663 non-null   object
 19  pharmacie                    1591 non-null   object
 20  hopital                      1362 non-null   object
 21  marche                       1573 non-null   object
 22  magasin                      1559 non-null   object
 23  bar                          1112 non-null   object
 24  restaurant                   1645 non-null   object
 25  region                       1795 non-null   object
 26  type                         1795 non-null   object
 27  transport                    1531 non-null   object
 28  services.group.2.nome-macro  195 non-null    object
 29  services.group.0.nome-macro  55 non-null     object
 30  services.group.6.nome-macro  48 non-null     object
 31  last_published_at            1795 non-null   datetime64[ns]
 32  caracteristiques             1795 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(27)
memory usage: 462.9+ KB

,titre,adresse,description,url,latitude,longitude,prix,surface,pieces,ville,...,bar,restaurant,region,type,transport,services.group.2.nome-macro,services.group.0.nome-macro,services.group.6.nome-macro,last_published_at,caracteristiques
0,Villa jumelée en vente,Rue Bhira,<p>Villa à deux étages offrant de beaux volume...,https://www.tecnocasa.tn/vendre/villa/bizerte/...,37.293402,9.854981,550000,196,None,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,villa,NaN,NaN,NaN,NaN,2026-01-21 12:40:58,[]
1,S+2 en vente,Rue soltana,"<p> Cet appartement <strong data-start=""125"" d...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.289502,9.848741,330000,130,3 pièces,bizerte,...,NaN,"[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'bus', 'subclass...",NaN,NaN,NaN,2026-01-13 15:09:03,[]
2,Triplex en vente,Borj taleb,"<p data-start=""0"" data-end=""709"" data-is-last-...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.279702,9.843971,200000,205,None,bizerte,...,NaN,"[{'name': 'The Garage', 'class': 'restaurant',...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-12-15 18:06:31,[]
3,S+2 en vente,Beb mateur,<p>Cet appartemen Situé au <strong>deuxième ét...,https://www.tecnocasa.tn/vendre/appartement/bi...,37.267202,9.868231,150000,51,3 pièces,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Restaurants', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-09-03 11:57:17,[]
4,S+2 en vente,Rue Rawebi,"<p> cet appartement <strong data-start=""82"" da...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.284502,9.870201,330000,100,3 pièces,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-12-04 18:17:08,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1790,S+3 en location,Route de la Plage,"<p data-start=""76"" data-end=""390"">Cet appartem...",https://www.tecnocasa.tn/louer/appartement/sou...,35.866500,10.610700,1800,160,4 pièces,khezama,...,"[{'name': 'Menchia', 'class': 'bar', 'subclass...","[{'name': 'Le QG', 'class': 'restaurant', 'sub...",centre-est-ce,appartement,"[{'name': 'Sousse-Hammam Sousse', 'class': 'bu...",NaN,NaN,NaN,2025-08-16 15:12:55,[]
1791,S+3 en location,Rue marrakech,"<p data-start=""69"" data-end=""246"">Situé dans u...",https://www.tecnocasa.tn/louer/appartement/sou...,35.844000,10.616800,2100,200,3 pièces,khezama,...,"[{'name': 'Vanilla', 'class': 'bar', 'subclass...","[{'name': 'Malibu', 'class': 'restaurant', 'su...",centre-est-ce,appartement,"[{'name': 'Sousse', 'class': 'railway', 'subcl...",NaN,Balcon,NaN,2025-09-11 15:30:08,[Balcon]
1792,Etage de villa en location,Sahloul 4,<p>À louer : spacieux appartement S+3 de 190 m...,https://www.tecnocasa.tn/louer/villa/sousse/sa...,35.834102,10.609723,1200,0,None,sahloul,...,"[{'name': 'Vanilla', 'class': 'bar', 'subclass...","[{'name': 'Claudio', 'class': 'restaurant', 's...",centre-est-ce,villa,"[{'name': 'Sousse', 'class': 'railway', 'subcl...",NaN,NaN,NaN,2025-08-28 14:01:08,[]
1793,Terrain agricole en location,Sidi Bouali n°2,<p>Ce terrain bénéficie d’un emplacement strat...,https://www.tecnocasa.tn/louer/terrain/sousse/...,35.937300,10.506900,11000,3150,None,sidi-bou-ali,...,NaN,NaN,centre-est-ce,terrain,NaN,NaN,NaN,NaN,2025-08-26 15:25:11,[]
1794,S+2 en location,appartement rue des palmiers,<p>Cet appartement est distingué par son stand...,https://www.tecnocasa.tn/louer/appartement/sou...,35.849200,10.610500,1300,0,None,khezama,...,"[{'name': 'BORA BORA Disco', 'class': 'bar', '...","[{'name': 'Mare-mar Ouahchi', 'class': 'restau...",centre-est-ce,appartement,"[{'name': 'Sousse-Hammam Sousse- Sahloul', 'cl...",NaN,NaN,NaN,2024-07-20 11:15:22,[]

In [305]:
import ast

def add_features_to_caracteristiques(row):
    # Ensure caracteristiques is a list
    if isinstance(row['caracteristiques'], str):
        try:
            features_list = ast.literal_eval(row['caracteristiques'])
        except:
            features_list = []
    elif isinstance(row['caracteristiques'], list):
        features_list = row['caracteristiques']
    else:
        features_list = []

    # Add features if value == 1
    if row.get('clim') == 1:
        features_list.append("clim")

    if row.get('ascenseur') == 1:
        features_list.append("ascenseur")

    if row.get('chauffage') == 1:
        features_list.append("chauffage")

    if row.get('jardin') == 1:
        features_list.append("jardin")

    return list(set(features_list))  # remove duplicates if any


df_tecnocasa_std['caracteristiques'] = df_tecnocasa_std.apply(add_features_to_caracteristiques, axis=1)

df_tecnocasa_std['caracteristiques'].value_counts()

caracteristiques
[]                                                 1543
[Balcon]                                             61
[Terrasse]                                           42
[Ascenseur]                                          20
[Place de parking]                                   19
[Jardin]                                             12
[Interphone]                                          9
[Potager/Jardin Potager]                              8
[Garage]                                              6
[Entrée indépendante]                                 5
[Ascenseur, Place de parking]                         5
[Balcon, Place de parking]                            5
[cour intérieure]                                     4
[Terrasse, Jardin]                                    3
[Gardien]                                             3
[Vidéophone]                                          3
[Terrasse, Garage]                                    3
[Plafond]                                             2
[Balcon, Parking public]                              2
[Alarme]                                              2
[Escalier extérieure]                                 2
[Four]                                                2
[Pergola/Abris]                                       2
[Réception]                                           2
[Parking public]                                      2
[Parking public, Balcon]                              2
[Balcon, Poutres Apparentes]                          1
[Terrasse, Entrée indépendante]                       1
[Cafétéria, Balcon, Place de parking]                 1
[Balcon, Brique]                                      1
[Doublure ..., Balcon, Enduction, Recouvrement]       1
[Plafond, Terrasse]                                   1
[cour intérieure, Terrasse]                           1
[Terrasse, Place de parking]                          1
[Balcon, Pergola/Abris, Place de parking]             1
[Interphone, Balcon]                                  1
[Four, Jardin]                                        1
[Balcon, Ascenseur]                                   1
[Aire de jeux]                                        1
[Balcon, Jardin, Place de parking]                    1
[Balcon, Rustique]                                    1
[Balcon, Système anti-incendie]                       1
[Divisé]                                              1
[Alarme, Balcon, Escalier extérieure]                 1
[Balcon, Entrée indépendante]                         1
[Jardin, Place de parking]                            1
[Réception, Place de parking]                         1
[Brique]                                              1
[Doublure ..., Enduction, Recouvrement]               1
[Terrasse, Potager/Jardin Potager]                    1
[Terrasse, Ascenseur]                                 1
[Alarme, Ascenseur]                                   1
Name: count, dtype: int64

**missing :** code_postal ...

Quick Pre-clean steps

Numeric conversion:

prix, surface, chambres, annee_constr, etage → convert to numeric (some are objects).

Datetime:

last_published_at → ensure it’s datetime64 (already seems fine).

Binary / features:

Columns like clim, ascenseur, chauffage, jardin → convert to 0/1 integers.

Fill NaNs:

Numeric → fill with 0 or median if appropriate.

Categorical → fill with "unknown".

Strip strings:

For object columns like ville, contrat, standing → remove extra spaces.

In [306]:
columns = [
    "etage",
    "pieces",
]
for col in columns:
    if col in df_tecnocasa_std.columns:
        print (f"Unique values in column '{col}':")
        values = df_tecnocasa_std[col].dropna().unique()
        print(values)

Unique values in column 'etage':
[2 5 3 1 '' 'Terre' '4 (étage elevé)' '1 (étage moyen)' 4 '3 (étage bas)'
 6 'Moyen' '1 (étage terre)' '1 (étage bas)' '5 (étage elevé)' 'Bas'
 '2 (étage bas)' '3 (étage moyen)' '2 (étage moyen)' '3 (étage mezzanine)'
 '1 (étage elevé)' '2 (étage terre)' '3 (étage elevé)' '4 (étage dernier)'
 '2 (étage elevé)' '2 (étage dernier)' '6 (étage elevé)'
 '2 (étage grenier)' '3 (étage terre)' '6 (étage dernier)'
 '4 (étage moyen)' 'Elevé' '7 (étage elevé)' 'Dernier' 'Grenier'
 '1 (étage dernier)' '4 (étage grenier)' '2 (étage sous-sol)'
 '7 (étage moyen)' '9 (étage elevé)' '3 (étage dernier)' '5 (étage moyen)'
 'Sous-sol' '-2 (étage bas)' 7 '8 (étage dernier)' '1 (étage grenier)'
 'Sot' '7 (étage dernier)' '-1 (étage sot)' '6 (étage moyen)'
 '4 (étage bas)' '8 (étage elevé)' '6 (étage grenier)' '-1 (étage bas)']
Unique values in column 'pieces':
['3 pièces' '4 pièces' '1 pièce' '6 pièces' '2 pièces' '5 pièces'
 '8 pièces' '7 pièces']

In [307]:
import pandas as pd
import numpy as np

df = df_tecnocasa_std.copy()  # keep original safe

# ----------------------------
# 1. Numeric conversion
# ----------------------------
# Convert to numeric
# basic numeric columns
for col in ['annee_constr', 'prix', 'surface']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

# features that may have non-numeric chars
# Example: "3 pieces" -> 3, "4 pièces" -> 4
if 'pieces' in df.columns:
    df['pieces'] = df['pieces'].astype(str).str.extract('(\d+)').astype('Int64')

if 'etage' in df.columns:
    manual_mapping = {
    'RDC': 0,
    'Terre': 0,
    'Sous-sol': -1,
    'Sot': -1,
    'Bas': 1,
    'Moyen': 2,
    'Elevé': 3,
    'Dernier': np.nan,  # optional: choose max floor or leave NaN
    'Grenier': np.nan   # optional: choose a value
}

def process_floor(val):
    val_str = str(val).strip()
    
    # If empty, return NaN
    if val_str == '':
        return np.nan
    
    # Try extracting first number
    num = pd.Series([int(x) for x in val_str if x.isdigit()])
    if not num.empty:
        return int(num.iloc[0])
    
    # If no number, check mapping
    return manual_mapping.get(val_str, np.nan)  # default NaN if unknown

# Apply function
df['etage'] = df['etage'].apply(process_floor).astype('Int64')
print(df['etage'].unique())



# ----------------------------
# 2. Binary features: convert to 0/1
# ----------------------------
binary_cols = ['clim', 'ascenseur', 'chauffage', 'jardin']
for col in binary_cols:
    if col in df.columns:
        df[col] = df[col].apply(lambda x: 1 if str(x).strip().lower() in ['yes','oui','true','1'] else 0)
        df[col] = df[col].fillna(0).astype(int)


# ----------------------------
# 3. Fill NaNs
# ----------------------------
# Numeric columns
#numeric_cols = ['prix', 'surface', 'pieces', 'etage', 'annee_constr']
#for col in numeric_cols:
#    if col in df.columns:
#        df[col] = df[col].fillna(0)

# Categorical columns
categorical_cols = ['ville','contrat','standing','region','type','transport']
for col in categorical_cols:
    if col in df.columns:
        df[col] = df[col].fillna('unknown').astype(str).str.strip()

# ----------------------------
# 4. Feature columns already numeric, ensure int
# ----------------------------
feature_cols = ['aire_jeux','alarme','ascenseur_bat','balcon','brique','cafeteria','divise',
                'doublure','enduction','entree_indep','escalier_ext','four','garage','gardien',
                'interphone','jardin_ext','parking_pub','pergola_abris','place_parking','plafond',
                'potager','poutres','recouvrement','rustique','reception','anti_incendie','terrasse',
                'videophone','cour_interieure']
for col in feature_cols:
    if col in df.columns:
        df[col] = df[col].fillna(0).astype(int)

# ----------------------------
# 5. Ensure datetime
# ----------------------------
if 'last_published_at' in df.columns:
    df['last_published_at'] = pd.to_datetime(df['last_published_at'], errors='coerce')

# ----------------------------
# Done
# ----------------------------

df_tecnocasa_std = df.copy()  # save cleaned version

print("Pre-clean done! Sample:")
df

<IntegerArray>
[2, 5, 3, 1, <NA>, 0, 4, 6, 7, 9, -1, 8]
Length: 12, dtype: Int64
Pre-clean done! Sample:

,titre,adresse,description,url,latitude,longitude,prix,surface,pieces,ville,...,bar,restaurant,region,type,transport,services.group.2.nome-macro,services.group.0.nome-macro,services.group.6.nome-macro,last_published_at,caracteristiques
0,Villa jumelée en vente,Rue Bhira,<p>Villa à deux étages offrant de beaux volume...,https://www.tecnocasa.tn/vendre/villa/bizerte/...,37.293402,9.854981,550000,196,<NA>,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,villa,unknown,NaN,NaN,NaN,2026-01-21 12:40:58,[]
1,S+2 en vente,Rue soltana,"<p> Cet appartement <strong data-start=""125"" d...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.289502,9.848741,330000,130,3,bizerte,...,NaN,"[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'bus', 'subclass...",NaN,NaN,NaN,2026-01-13 15:09:03,[]
2,Triplex en vente,Borj taleb,"<p data-start=""0"" data-end=""709"" data-is-last-...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.279702,9.843971,200000,205,<NA>,bizerte,...,NaN,"[{'name': 'The Garage', 'class': 'restaurant',...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-12-15 18:06:31,[]
3,S+2 en vente,Beb mateur,<p>Cet appartemen Situé au <strong>deuxième ét...,https://www.tecnocasa.tn/vendre/appartement/bi...,37.267202,9.868231,150000,51,3,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Restaurants', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-09-03 11:57:17,[]
4,S+2 en vente,Rue Rawebi,"<p> cet appartement <strong data-start=""82"" da...",https://www.tecnocasa.tn/vendre/appartement/bi...,37.284502,9.870201,330000,100,3,bizerte,...,"[{'name': 'The Palm Garden Bar', 'class': 'bar...","[{'name': 'Bake & Bake', 'class': 'restaurant'...",nord-est-ne,appartement,"[{'name': 'Bizerte', 'class': 'railway', 'subc...",NaN,NaN,NaN,2025-12-04 18:17:08,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1790,S+3 en location,Route de la Plage,"<p data-start=""76"" data-end=""390"">Cet appartem...",https://www.tecnocasa.tn/louer/appartement/sou...,35.866500,10.610700,1800,160,4,khezama,...,"[{'name': 'Menchia', 'class': 'bar', 'subclass...","[{'name': 'Le QG', 'class': 'restaurant', 'sub...",centre-est-ce,appartement,"[{'name': 'Sousse-Hammam Sousse', 'class': 'bu...",NaN,NaN,NaN,2025-08-16 15:12:55,[]
1791,S+3 en location,Rue marrakech,"<p data-start=""69"" data-end=""246"">Situé dans u...",https://www.tecnocasa.tn/louer/appartement/sou...,35.844000,10.616800,2100,200,3,khezama,...,"[{'name': 'Vanilla', 'class': 'bar', 'subclass...","[{'name': 'Malibu', 'class': 'restaurant', 'su...",centre-est-ce,appartement,"[{'name': 'Sousse', 'class': 'railway', 'subcl...",NaN,Balcon,NaN,2025-09-11 15:30:08,[Balcon]
1792,Etage de villa en location,Sahloul 4,<p>À louer : spacieux appartement S+3 de 190 m...,https://www.tecnocasa.tn/louer/villa/sousse/sa...,35.834102,10.609723,1200,0,<NA>,sahloul,...,"[{'name': 'Vanilla', 'class': 'bar', 'subclass...","[{'name': 'Claudio', 'class': 'restaurant', 's...",centre-est-ce,villa,"[{'name': 'Sousse', 'class': 'railway', 'subcl...",NaN,NaN,NaN,2025-08-28 14:01:08,[]
1793,Terrain agricole en location,Sidi Bouali n°2,<p>Ce terrain bénéficie d’un emplacement strat...,https://www.tecnocasa.tn/louer/terrain/sousse/...,35.937300,10.506900,11000,3150,<NA>,sidi-bou-ali,...,NaN,NaN,centre-est-ce,terrain,unknown,NaN,NaN,NaN,2025-08-26 15:25:11,[]
1794,S+2 en location,appartement rue des palmiers,<p>Cet appartement est distingué par son stand...,https://www.tecnocasa.tn/louer/appartement/sou...,35.849200,10.610500,1300,0,<NA>,khezama,...,"[{'name': 'BORA BORA Disco', 'class': 'bar', '...","[{'name': 'Mare-mar Ouahchi', 'class': 'restau...",centre-est-ce,appartement,"[{'name': 'Sousse-Hammam Sousse- Sahloul', 'cl...",NaN,NaN,NaN,2024-07-20 11:15:22,[]

### Monbien / immobilier.tn / annonces_immobilieres ( meme schema )

In [308]:
df_monbien_std = df_monbien.rename(columns={
    "transaction": "contrat",
    "type_bien": "type",
    "surface_m2": "surface",
    "localisation": "ville",
    "caracteristiques_csv": "POI",
    "images_csv": "images"
})

df_monbien_std["pieces"] = df_monbien_std["pieces"].astype(str).str.extract('(\d+)')[0].astype('Int64') +1 
df_monbien_std["prix"] = (
    df_monbien_std["prix"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)  # remove everything except digits
    .astype("float64")
)
df_monbien_std = df_monbien_std.drop(["chambres", "annonce_id", "source","salles_de_bain","details_csv"], axis=1)
df_monbien_std

,url,contrat,type,titre,prix,surface,pieces,ville,adresse,description,images,POI
0,https://www.monbien.tn/properties/7599/terrain...,Vente,Terrain,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...,0.0,4018,<NA>,,,Réf: THS063 Nabeul / Hammamet Terrain / à vend...,https://www.monbien.tn/media/cache/resolve/pho...,Terrain de 4018 m² à vendre à 200 dt/m² à hamm...
1,https://www.monbien.tn/properties/7592/coquet-...,Vente,Appartement,Coquet studio à vendre à 140 md à hammamet 513...,140000.0,,2,,,Réf: AH077 Nabeul / Hammamet Appartement / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Coquet studio à vendre à 140 md à hammamet 513...
2,https://www.monbien.tn/properties/7588/villa-t...,Vente,Villa,Villa toute neuve s+3 avec piscine à hammamet ...,650000.0,200,4,,,Réf: MHS186 Nabeul / Hammamet Villa / à vendre...,https://www.monbien.tn/media/cache/resolve/pho...,Villa toute neuve s+3 avec piscine à hammamet ...
3,https://www.monbien.tn/properties/7596/un-dupl...,Vente,Terrain,Un duplex avec piscine à hammamet nord à vendr...,730000.0,220,4,,,Réf: MH112 Nabeul / Hammamet nord Duplex / à v...,https://www.monbien.tn/media/cache/resolve/pho...,Un duplex avec piscine à hammamet nord à vendr...
4,https://www.monbien.tn/properties/7594/apparte...,Vente,Appartement,Appartement s+1 avec vue de mer à hammamet à v...,320000.0,76,2,,,Réf: AH079 Nabeul / Hammamet centre Appartemen...,https://www.monbien.tn/media/cache/resolve/pho...,Appartement s+1 avec vue de mer à hammamet à v...
...,...,...,...,...,...,...,...,...,...,...,...,...
6934,https://www.monbien.tn/properties/7077/bel-app...,Vente,Appartement,Bel appartement s+1 à vendre à afh mrezga 5135...,250000.0,90,2,,,Réf: AM091 Nabeul / Mrezga Appartement / à ven...,https://www.monbien.tn/media/cache/resolve/pho...,Bel appartement s+1 à vendre à afh mrezga 5135...
6935,https://www.monbien.tn/properties/4831/villa-a...,Location,Villa,"Villa azur à louer à sidi daoud, la marsa",4200.0,,<NA>,,,Réf: OF91933 Tunis / La marsa Villa / à louer ...,https://www.monbien.tn/media/cache/resolve/pho...,"Villa azur à louer à sidi daoud, la marsa | Vi..."
6936,https://www.monbien.tn/properties/4840/appart-...,Location,Appartement,Appart s3 rano à louer à cité el ghazela,1100.0,,<NA>,,,Réf: OF92209 Ariana / Ghazela Appartement / à ...,https://www.monbien.tn/media/cache/resolve/pho...,Appart s3 rano à louer à cité el ghazela | App...
6937,https://www.monbien.tn/properties/4848/duplex-...,Location,Duplex,Duplex harmonia à louer à golden tulip,2900.0,,<NA>,,,Réf: OF92205 Tunis / Gammarth Duplex / à louer...,https://www.monbien.tn/media/cache/resolve/pho...,Duplex harmonia à louer à golden tulip | Duple...
6938,https://www.monbien.tn/properties/6434/2-lots-...,Vente,Terrain,2 lots de terrain vue de mer à vendre à jinen ...,0.0,482,<NA>,,,Réf: TBK003 Nabeul / Béni khiar Terrain / à ve...,https://www.monbien.tn/media/cache/resolve/pho...,2 lots de terrain vue de mer à vendre à jinen ...

In [309]:
df_annonces_immobilieres_std = df_annonces_immobilieres.rename(columns={
    "transaction": "contrat",
    "type_bien": "type",
    "surface_m2": "surface",
    "localisation": "ville",
    "caracteristiques_csv": "POI",
    "images_csv": "images"
})

df_annonces_immobilieres_std["pieces"] = df_annonces_immobilieres_std["pieces"].astype(str).str.extract('(\d+)')[0].astype('Int64') +1 
df_annonces_immobilieres_std["prix"] = (
    df_annonces_immobilieres_std["prix"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)  # remove everything except digits
    .astype("float64")
)
df_annonces_immobilieres_std = df_annonces_immobilieres_std.drop(["chambres", "annonce_id", "source","salles_de_bain","details_csv"], axis=1)
df_annonces_immobilieres_std

ValueError: could not convert string to float: ''

In [ ]:
df_immobilier_com_tn_std = df_immobilier_com_tn.rename(columns={
    "transaction": "contrat",
    "type_bien": "type",
    "surface_m2": "surface",
    "localisation": "ville",
    "caracteristiques_csv": "POI",
    "images_csv": "images"
})

df_immobilier_com_tn_std["pieces"] = df_immobilier_com_tn_std["pieces"].astype(str).str.extract('(\d+)')[0].astype('Int64') +1 
df_immobilier_com_tn_std["prix"] = (
    df_immobilier_com_tn_std["prix"]
    .astype(str)
    .str.replace(r"[^\d]", "", regex=True)  # remove everything except digits
    .astype("float64")
)
df_immobilier_com_tn_std = df_immobilier_com_tn_std.drop(["chambres", "annonce_id", "source","salles_de_bain","details_csv"], axis=1)
df_immobilier_com_tn_std

### Tunisie Annonce

In [ ]:
df_tunisie_annonce_std = df_tunisie_annonces.rename(columns={
    "title_full": "titre",
    "description_full": "description",
    "locality": "adresse",
    "detail_url": "url",
    "price_tnd": "prix",
    "surface_m2": "surface",
    "governorate": "ville",
    "property_subtype" : "type",
    "date_posted": "date_publication",
    "category_type": "contrat",
})
df_tunisie_annonce_std

,location,ville,delegation,adresse,property_type,type,title,description_preview,prix,price_raw,...,price_detail,price_eur,price_usd,price_cad,price_dzd,price_mad,description,date_inserted,date_modified,address
0,Ariana,Ariana,Ariana Ville,Ariana,Location,App. 4 pièc,S plus 3 a l'ariana,S plus 3 a l ariana wb4420,1200.0,1 200,...,1 200 Dinar Tunisien (TND),367,422,547,50 092,4 001,l'agence immo contact met en location a l'aria...,15/02/2026,15/02/2026,NaN
1,Ariana,Ariana,Ariana Ville,Ariana,Location,App. 3 pièc,Appartement borj louzir,Appartement borj louzir,550.0,550,...,550 Dinar Tunisien (TND),168,193,251,22 959,1 834,belle appartement au rez-de-chaussé. situé à b...,15/02/2026,15/02/2026,borj louzir
2,El Omrane Super,Tunis,El Omrane Superieur,El Omrane Superieur,Location,App. 1 pièc,Studio pour fille ou cou,Studio pour fille ou coupe a 100m arrêt de métro,350.0,350,...,350 Dinar Tunisien (TND),107,123,159,14 610,1 167,"pour filles ou jeune coupe marié, un petit s+1...",29/04/2025,15/02/2026,a 100m arrêt de métro ettadhamen
3,Berge Du Lac,Tunis,La Marsa,Berge Du Lac,Bureaux & Commer,Surfaces,Local commercial 2000 d,Local commercial 2000 d lac 1,2000.0,2 000,...,2 000 Dinar Tunisien (TND),612,703,911,83 487,6 668,les berges du lac 1 opportunité à saisir lo...,20/01/2026,15/02/2026,les berges du lac 1
4,Hammamet,Nabeul,Hammamet,Hammamet,Vente,Maisons,Villa manhattan,Villa manhattan,1050000.0,1 050 000,...,1 050 000 Dinar Tunisien (TND),321 101,369 009,478 280,43 830 596,3 500 835,à vendre chez green immobilier une demeure bie...,04/05/2025,15/02/2026,hammamet nord
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15167,Hammamet,Nabeul,Hammamet,Hammamet,Vente,Maisons,V536 villa suisse 2 hamm,V536 villa suisse 2 hammamet nord villa,750000.0,750 000,...,750 000 Dinar Tunisien (TND),229 358,263 578,341 628,31 307 569,2 500 596,v536 villa suisse 2\na vendre chez l’agence sm...,31/10/2025,31/10/2025,hammamet
15168,Jardins de Cart,Tunis,Ain Zaghouan,Jardins de Carthage,Location,App. 3 pièc,Un charmant apparemment s2 au,Un charmant apparemment s2 au jardins de carthage,2300.0,2 300,...,2 300 Dinar Tunisien (TND),703,808,1 048,96 010,7 668,un bel appartement s2 situé dans une résidence...,27/09/2025,31/10/2025,jardins de carthage
15169,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,Reez de chaussez s2 à b jezir,Reez de chaussez s2 à b jezira tn,600.0,600,...,600 Dinar Tunisien (TND),183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz
15170,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,S2 au centre ville de tunis,S2 au centre ville de tunis,600.0,600,...,600 Dinar Tunisien (TND),183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz
15171,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,Trois pièces à beb el jezira,Trois pièces à beb el jezira rdc,600.0,600,...,600 Dinar Tunisien (TND),183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz

In [ ]:
df_tunisie_annonce_std['contrat'].value_counts()

contrat
Location               5992
Vente                  4681
Terrain                3392
Bureaux & Commerces     872
Location vacances       206
Achat                    17
Partage                  12
Name: count, dtype: int64

In [ ]:
df_tunisie_annonce_std['type'].value_counts()

type
Maisons        3020
Terrain nu     2387
App. 3 pièc    2071
App. 2 pièc    1711
App. 1 pièc    1129
App. 4 pièc    1065
Terrain agr    1005
Surfaces        854
Bureau          580
Autre           537
Duplex          361
App. 5 pièc     286
Fond de Com      92
Gérance lib      37
Atelier          37
Name: count, dtype: int64

In [ ]:
df_tunisie_annonce_std['pieces'] = df_tunisie_annonce_std['type'].astype(str).str.extract('(\d+)').astype('Int64')
df_tunisie_annonce_std['pieces'].value_counts()

pieces
3    2071
2    1711
1    1129
4    1065
5     286
Name: count, dtype: Int64

In [ ]:
df_tunisie_annonce_std

,location,ville,delegation,adresse,property_type,type,title,description_preview,prix,price_raw,...,price_eur,price_usd,price_cad,price_dzd,price_mad,description,date_inserted,date_modified,address,pieces
0,Ariana,Ariana,Ariana Ville,Ariana,Location,App. 4 pièc,S plus 3 a l'ariana,S plus 3 a l ariana wb4420,1200.0,1 200,...,367,422,547,50 092,4 001,l'agence immo contact met en location a l'aria...,15/02/2026,15/02/2026,NaN,4
1,Ariana,Ariana,Ariana Ville,Ariana,Location,App. 3 pièc,Appartement borj louzir,Appartement borj louzir,550.0,550,...,168,193,251,22 959,1 834,belle appartement au rez-de-chaussé. situé à b...,15/02/2026,15/02/2026,borj louzir,3
2,El Omrane Super,Tunis,El Omrane Superieur,El Omrane Superieur,Location,App. 1 pièc,Studio pour fille ou cou,Studio pour fille ou coupe a 100m arrêt de métro,350.0,350,...,107,123,159,14 610,1 167,"pour filles ou jeune coupe marié, un petit s+1...",29/04/2025,15/02/2026,a 100m arrêt de métro ettadhamen,1
3,Berge Du Lac,Tunis,La Marsa,Berge Du Lac,Bureaux & Commer,Surfaces,Local commercial 2000 d,Local commercial 2000 d lac 1,2000.0,2 000,...,612,703,911,83 487,6 668,les berges du lac 1 opportunité à saisir lo...,20/01/2026,15/02/2026,les berges du lac 1,<NA>
4,Hammamet,Nabeul,Hammamet,Hammamet,Vente,Maisons,Villa manhattan,Villa manhattan,1050000.0,1 050 000,...,321 101,369 009,478 280,43 830 596,3 500 835,à vendre chez green immobilier une demeure bie...,04/05/2025,15/02/2026,hammamet nord,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15167,Hammamet,Nabeul,Hammamet,Hammamet,Vente,Maisons,V536 villa suisse 2 hamm,V536 villa suisse 2 hammamet nord villa,750000.0,750 000,...,229 358,263 578,341 628,31 307 569,2 500 596,v536 villa suisse 2\na vendre chez l’agence sm...,31/10/2025,31/10/2025,hammamet,<NA>
15168,Jardins de Cart,Tunis,Ain Zaghouan,Jardins de Carthage,Location,App. 3 pièc,Un charmant apparemment s2 au,Un charmant apparemment s2 au jardins de carthage,2300.0,2 300,...,703,808,1 048,96 010,7 668,un bel appartement s2 situé dans une résidence...,27/09/2025,31/10/2025,jardins de carthage,3
15169,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,Reez de chaussez s2 à b jezir,Reez de chaussez s2 à b jezira tn,600.0,600,...,183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz,3
15170,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,S2 au centre ville de tunis,S2 au centre ville de tunis,600.0,600,...,183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz,3
15171,Bab El Jazira,Tunis,Bab Bhar,Bab El Jazira,Location,App. 3 pièc,Trois pièces à beb el jezira,Trois pièces à beb el jezira rdc,600.0,600,...,183,211,273,25 046,2 000,a louer un appart s2 situé à tunis centre vill...,01/11/2025,01/11/2025,tunis centre ville : bab jezirz,3

In [ ]:
columns_to_extract = [
"ville",
"adresse",
"type",
"prix",
"date_publication",
"url",
"titre",
"description",
"contrat",
"surface",
"pieces"
]
df_tunisie_annonce_std = df_tunisie_annonce_std[columns_to_extract]
df_tunisie_annonce_std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15172 entries, 0 to 15171
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ville             15172 non-null  object
 1   adresse           15172 non-null  object
 2   type              15172 non-null  object
 3   prix              15124 non-null  float64
 4   date_publication  15172 non-null  object
 5   url               15172 non-null  object
 6   titre             15172 non-null  object
 7   description       15172 non-null  object
 8   contrat           15172 non-null  object
 9   surface           14256 non-null  float64
 10  pieces            6262 non-null   Int64
dtypes: Int64(1), float64(2), object(8)
memory usage: 1.3+ MB

### BigDatis

In [ ]:
df_bigdatis

,id,idsAlt,sources,title,description,price,area,flags,thumbnailUrl,images,...,modifiedAt,priceDroppedAt,timestamp,priceTimestamp,comments,commentsCount,properties.transactionType,properties.sellerType,properties.propertyType,properties.typology
0,1254077,[],"[{'sourceId': 2, 'lastModified': 1771701898, '...",محل تجاري للكراء,📢 محل تجاري للكراء – خزامة الغربية (سوسة)\n\nم...,500.0,NaN,[],56215/28107556_f4b0b0f8b8b87cfe.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 19:24:58,2026-02-21 19:24:56,2026-02-21 19:24:58,2026-02-21 19:24:56,[],0,rental,private,commercialPremise,NaN
1,1254079,[],"[{'sourceId': 2, 'lastModified': 1771703278, '...",a louer s+1 haut standing,🏡 À louer – 3 Appartements de type S+1 neufs ....,800.0,55.0,[new],56215/28107562_80b8393191904056.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 19:47:58,2026-02-21 19:47:56,2026-02-21 19:47:58,2026-02-21 19:47:56,[],0,rental,agency,flat,s+1
2,1254083,[],"[{'sourceId': 12, 'lastModified': None, 'price...",دار للكراء للطالبات,حي لحبيب شارع سيدي عبيد نهج مقابل توابل ملاك ...,NaN,NaN,[],56215/28107578_eade3c3e3d387ccb.jpg,[{'url': 'https://b3g4.fra01.idrivee2-68.com/i...,...,None,None,NaT,None,[],0,rental,private,house,NaN
3,1254081,[],"[{'sourceId': 2, 'lastModified': 1771707510, '...",Local commercial 15 m²,"à louer local commercial,\nemplacement :\nsitu...",1400.0,15.0,[],56215/28107603_33d4b2fefa7e7d3f.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 20:58:30,2026-02-20 23:00:00,2026-02-21 20:58:30,2026-02-20 23:00:00,[],0,rental,private,commercialPremise,NaN
4,1183174,[],"[{'sourceId': 14, 'lastModified': 1771707661, ...",S+1 en location,"Cet appartement, jamais habité, est situé au p...",350.0,70.0,[new],56215/28107604_f7b4b3b0b4bc34c4.jpg,[{'url': 'https://cdn-media.medialabtc.it/tn/a...,...,2026-02-21 21:01:01,2025-11-01 09:21:13,2026-02-21 21:01:01,2025-11-01 09:21:13,[],0,rental,agency,flat,s+1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27043,1251466,[1251839],"[{'sourceId': 2, 'lastModified': 1771700104, '...",MENZAH 9 B : APPARTEMENT S+2 À LOUER,📍MENZAH 9 B : APPARTEMENT S+2 À LOUER \n\nL’a...,1650.0,120.0,"[elevator, parking]",56215/28107535_114006460323f3c0.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:04,2026-02-15 23:00:00,2026-02-21 18:55:04,2026-02-15 23:00:00,[],0,rental,agency,flat,s+2
27044,1252481,[],"[{'sourceId': 2, 'lastModified': 1771700121, '...",📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,1450.0,NaN,[],56215/28107536_f8fcf8f8f9fcfef8.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:21,2026-02-11 23:00:00,2026-02-21 18:55:21,2026-02-11 23:00:00,[],0,rental,agency,villaFloor,s+2
27045,1251569,[],"[{'sourceId': 2, 'lastModified': 1771700143, '...",📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,4200.0,600.0,[],56215/28107537_11031921ab6b00ca.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:55:43,2026-02-16 15:03:14,2026-02-21 18:55:43,2026-02-16 15:03:14,[],0,rental,agency,house,s+7
27046,1210068,[1210134],"[{'sourceId': 2, 'lastModified': 1771700169, '...",📍 CITE ENNOZHA - ARIANA : DES BUREAUX H+2 À LOUER,L’agence #MON_RÉSEAU met à la location des bur...,1150.0,NaN,[],56215/28107538_e1e1f1715bdbfaf2.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:56:09,2025-12-14 20:04:36,2026-02-21 18:56:09,2025-12-14 20:04:36,[],0,rental,agency,office,a+2
27047,1109660,[1110068],"[{'sourceId': 2, 'lastModified': 1771700214, '...",ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A ...,📍ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A...,1200.0,70.0,"[furnished, elevator, parking, balcony, heatin...",56215/28107539_3ab131686868c8cc.jpg,[{'url': 'https://storage.googleapis.com/tayar...,...,2026-02-21 18:56:54,2025-08-04 12:27:06,2026-02-21 18:56:54,2025-08-04 12:27:06,[],0,rental,agency,flat,s+1

In [ ]:
columns_to_extract = [
    "title",
    "description",
    "price",
    "area",
    "flags",
    "images",
    "modifiedAt",
    "properties.transactionType",
    "properties.propertyType",
    "properties.typology",
    "locationId"
]

df_bigdatis_std = df_bigdatis[columns_to_extract].copy()

df_bigdatis_std = df_bigdatis_std.rename(columns={
    "title": "titre",
    "description": "description",
    "price": "prix",
    "area": "surface",
    "flags":"caracteristiques",
    "images": "images",
    "modifiedAt": "date_publication",
    "properties.transactionType": "contrat",
    "properties.propertyType": "type",
    "properties.typology": "pieces",
    "locationId": "ville",
})

df_bigdatis_std

,titre,description,prix,surface,caracteristiques,images,modifiedAt,contrat,type,pieces,ville
0,محل تجاري للكراء,📢 محل تجاري للكراء – خزامة الغربية (سوسة)\n\nم...,500.0,NaN,[],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 19:24:58,rental,commercialPremise,NaN,4593
1,a louer s+1 haut standing,🏡 À louer – 3 Appartements de type S+1 neufs ....,800.0,55.0,[new],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 19:47:58,rental,flat,s+1,3225
2,دار للكراء للطالبات,حي لحبيب شارع سيدي عبيد نهج مقابل توابل ملاك ...,NaN,NaN,[],[{'url': 'https://b3g4.fra01.idrivee2-68.com/i...,None,rental,house,NaN,3900
3,Local commercial 15 m²,"à louer local commercial,\nemplacement :\nsitu...",1400.0,15.0,[],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 20:58:30,rental,commercialPremise,NaN,3961
4,S+1 en location,"Cet appartement, jamais habité, est situé au p...",350.0,70.0,[new],[{'url': 'https://cdn-media.medialabtc.it/tn/a...,2026-02-21 21:01:01,rental,flat,s+1,3082
...,...,...,...,...,...,...,...,...,...,...,...
27043,MENZAH 9 B : APPARTEMENT S+2 À LOUER,📍MENZAH 9 B : APPARTEMENT S+2 À LOUER \n\nL’a...,1650.0,120.0,"[elevator, parking]",[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 18:55:04,rental,flat,s+2,5208
27044,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,1450.0,NaN,[],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 18:55:21,rental,villaFloor,s+2,300
27045,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,4200.0,600.0,[],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 18:55:43,rental,house,s+7,309
27046,📍 CITE ENNOZHA - ARIANA : DES BUREAUX H+2 À LOUER,L’agence #MON_RÉSEAU met à la location des bur...,1150.0,NaN,[],[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 18:56:09,rental,office,a+2,301
27047,ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A ...,📍ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A...,1200.0,70.0,"[furnished, elevator, parking, balcony, heatin...",[{'url': 'https://storage.googleapis.com/tayar...,2026-02-21 18:56:54,rental,flat,s+1,300

In [ ]:
df_monbien_std["pieces"] = df_monbien_std["pieces"].astype(str).str.extract('(\d+)')[0].astype('Int64') +1

In [ ]:
df_bigdatis_std["contrat"].value_counts()

contrat
rental    27048
Name: count, dtype: int64

In [ ]:
df_bigdatis_std["contrat"] = df_bigdatis_std["contrat"].apply(lambda x: "location" if "rent" in x else "vente")
df_bigdatis_std["contrat"].value_counts()

contrat
location    27048
Name: count, dtype: int64

## Merging

In [ ]:
dataset_full_raw = pd.concat([df_monbien_std, df_tunisie_annonce_std, df_annonces_immobilieres_std, df_immobilier_com_tn_std, df_tecnocasa_std, df_bigdatis_std], ignore_index=True)
dataset_full_raw.info()

NameError: name 'df_immobilier_com_tn_std' is not defined